import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import TopBar from "../components/TopBar";
import ShadowBox from "../components/ShadowBox";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nexus</title>
        <meta name="description" content="Generated by Nexus" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <div className="p-4">
        <ShadowBox>
          <div>Identity</div>
          <div>Security</div>
          <div>Log out</div>
        </ShadowBox>
      </div>
    </>
  );
}
