import Head from "next/head";
import TopBar from "@/components/TopBar";
import { useState } from "react";
import WalletMenu from "@/components/Pages/Menu/WalletMenu";

export default function Home() {
  const [page, setPage] = useState<string>("Wallet");
  return (
    <>
      <Head>
        <title>Wallet</title>
        <meta name="description" content="Generated by Nexus" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <div className="p-4 flex items-start gap-4">
        <WalletMenu setPage={setPage} />

        {page === "Wallet" && <div>Wallet</div>}
        {page === "Transactions" && <div>Transactions</div>}
        {page === "Subscriptions" && <div>Subscriptions</div>}
      </div>
    </>
  );
}
