import Head from "next/head";
import TopBar from "../components/TopBar";
import ShadowBox from "../components/ShadowBox";
import Identity from "../components/Pages/Identity";
import { useState } from "react";

export default function Home() {
  const [page, setPage] = useState<string>("Identity");
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by Nexus" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <div className="p-4 flex items-start gap-4">
        <ShadowBox>
          <div className="cursor-pointer" onClick={() => setPage("Identity")}>
            Identity
          </div>
          <div className="cursor-pointer" onClick={() => setPage("Security")}>
            Security
          </div>
          <div className="cursor-pointer">Log out</div>
        </ShadowBox>
        {page === "Identity" && <Identity />}
        {page === "Security" && <div>Security</div>}
      </div>
    </>
  );
}
