import Head from "next/head";
import Image from "next/image";

export default function MarketPage() {
  return (
    <>
      <Head>
        <title> </title>
        <meta name="description" content="Generated by Nexus" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center align-center w-screen pt-10">
        <Image
          className="cursor-pointer "
          src="/svg/logo.svg"
          alt={""}
          width={50}
          height={50}
        />
      </div>
      <div className="flex justify-center align-center w-screen pt-10">
        <Image
          className="cursor-pointer "
          src="/LogoTypography.png"
          alt={""}
          width={300}
          height={50}
        />
      </div>
    </>
  );
}
