import Input from "@/components/Input";
import ProductsGrid from "@/components/ProductsGrid";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

export default function MarketPage() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title> </title>
        <meta name="description" content="Generated by Nexus" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center align-center w-screen pt-10">
        <Image
          className="cursor-pointer "
          src="/svg/logo.svg"
          alt={""}
          width={50}
          height={50}
        />
      </div>
      <div className="flex justify-center align-center w-screen pt-10">
        <Image
          className="cursor-pointer "
          src="/LogoTypography.png"
          alt={""}
          width={250}
          height={50}
        />
      </div>
      <div className="flex gap-5 justify-center align-center w-screen pt-10">
        <Input placeholder="Search" value="Flower" />
        <Image
          className="cursor-pointer -translate-x-12"
          src="/svg/search-icon.svg"
          alt={""}
          width={20}
          height={20}
          onClick={() => router.push("/search")}
        />
      </div>
      <ProductsGrid />
    </>
  );
}
