import SearchMenu from "@/components/Pages/Menu/SearchMenu";
import TopBar from "@/components/TopBar";
import Head from "next/head";
import { useState } from "react";

export default function SearchPage() {
  const [page, setPage] = useState<string>("My Ads");
  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by Nexus" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <div className="p-4 flex items-start gap-4">
        <SearchMenu setPage={setPage} />
        {page === "My Ads" && <div>My Ads</div>}
        {page === "My Spaces" && <div>My Spaces</div>}
        {page === "Space Marketplace" && <div>Space Marketplace</div>}
      </div>
    </>
  );
}
